name: wildpulse-quality-checks-ui-test

on:
  push:
    branches: [master, main]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
  pull_request:
    branches: [master, main]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
